OPENAI_API_KEY = ""

[connections.snowflake]
user = ""
password = ""
warehouse = ""
role = ""
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = ""
